trigger:
- main

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  sln: './src/casc.sln'
  tests: './src/CASC-Test/CASC-Test.csproj'

steps:
- script: dotnet build --configuration $(buildConfiguration) $(sln)
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet test $(tests) --logger "xunit;LogFileName=TestResults.xml"
  displayName: 'dotnet test'
- task: PublishTestResults@2
  displayName: 'publish test results to azure pipelines'
  inputs:
    testResultsFormat: 'xUnit'
    testResultsFiles: '**/TestResults.xml'