trigger:
- master

variables:
  buildConfiguration: 'Release'
  sln: './src/casc.sln'
  tests: './src/CASC-Test/CASC-Test.csproj'

jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - template: ./azure-release.yml

- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: ./azure-release.yml

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: ./azure-release.yml
  - script: sign